# Generated by Django 4.2 on 2023-08-07 14:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Activity",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                "db_table": "activity",
            },
        ),
        migrations.CreateModel(
            name="CollegeUser",
            fields=[
                (
                    "customuser_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "privilege",
                    models.CharField(
                        choices=[
                            ("superuser", "Superuser"),
                            ("principal", "Principal"),
                            ("hod", "HOD"),
                            ("employee", "Employee"),
                        ],
                        default="employee",
                        max_length=255,
                    ),
                ),
            ],
            options={
                "db_table": "user",
            },
            bases=("users.customuser",),
        ),
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                ("available_amount", models.IntegerField(default=0)),
                ("total_amount", models.IntegerField(default=0)),
            ],
            options={
                "db_table": "department",
            },
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=255, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("item", models.CharField(blank=True, max_length=255, null=True)),
                ("quantity", models.IntegerField(default=0)),
                ("requested_amount", models.IntegerField(default=0)),
                ("approved_amount", models.IntegerField(default=0)),
                ("file", models.FileField(blank=True, null=True, upload_to="uploads/")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("requested", "Requested"),
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                        ],
                        default="requested",
                        max_length=255,
                    ),
                ),
                ("note", models.TextField(blank=True, null=True)),
                (
                    "activity",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="api.activity",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="api.collegeuser",
                    ),
                ),
            ],
            options={
                "db_table": "transaction",
            },
        ),
        migrations.AddField(
            model_name="collegeuser",
            name="department",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="users",
                to="api.department",
            ),
        ),
        migrations.AddField(
            model_name="activity",
            name="department",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="activities",
                to="api.department",
            ),
        ),
    ]
