# Generated by Django 4.2 on 2023-08-28 14:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="activity",
            name="available_amount",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="activity",
            name="total_amount",
            field=models.IntegerField(default=0),
        ),
    ]
