# Generated by Django 4.1.4 on 2023-09-24 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_activity_available_amount_activity_total_amount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="file",
            field=models.FileField(blank=True, null=True, upload_to="media/"),
        ),
    ]
