# Generated by Django 4.1.4 on 2023-09-25 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_alter_transaction_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="activity",
            name="isActive",
            field=models.BooleanField(default=True),
        ),
    ]
